'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fib(num):
    a, b = 0, 1
    if num == 1 or num == 2: return 1
    else: return fib(num - 1) + fib(num - 2)

total = 0
i = 1

while fib(i) < 4000000:
    if not fib(i) % 2:
        total += fib(i)
    i += 1

print(total)